baseURL = 'https://wthblog.netlify.app/'
languageCode = 'en-us'
title = 'wth'
theme = 'PaperMod'

[params]
  ShowToc = true
  TocOpen = true
  env = "production" # ← 重要（これがないとOGPが無効になる場合あり）
  title = "wth"
  description = "洋画が好きなオタクのインターネット"
  images = ["images/ogp_wthblog.png"] # サイト共通OGP画像


[params.homeInfoParams]
Title = "Now playing"
Content = "洋画と洋ゲーが好きなオタクのインターネット"



[[params.socialIcons]]
name = "other"
url = "https://wavebox.me/wave/9deo799z47e4qr54/"

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "Contact"
name = "Contact"
url = "https://lit.link/havexit"
weight = 10

[params.assets]
favicon = "https://raw.githubusercontent.com/sezaki02/newwth/main/static/favicon.ico"
favicon16x16 = "https://raw.githubusercontent.com/sezaki02/newwth/main/static/favicon-16x16.png"
favicon32x32 = "https://raw.githubusercontent.com/sezaki02/newwth/main/static/favicon-32x32.png"
apple_touch_icon = "https://raw.githubusercontent.com/sezaki02/newwth/main/static/apple-touch-icon.png"
